# Generated by Django 4.0.5 on 2022-06-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_spent',
            field=models.IntegerField(default=0),
        ),
    ]
