# Generated by Django 4.0.5 on 2022-07-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Range',
            new_name='Period',
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(default='ahmedsellami', max_length=255),
            preserve_default=False,
        ),
    ]
