# Generated by Django 4.0.5 on 2022-06-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0002_alter_task_desc_alter_task_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
