# Generated by Django 4.0.5 on 2022-07-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0004_comment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.EmailField(default='ahmedsellami526@gmail.com', max_length=255),
        ),
    ]
