# Generated by Django 4.0.5 on 2022-07-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0005_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.EmailField(max_length=255),
        ),
    ]
