# Generated by Django 4.0.5 on 2022-07-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0007_alter_project_icon_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
