# Generated by Django 4.0.5 on 2022-07-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0008_alter_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='range',
            new_name='period',
        ),
        migrations.AddField(
            model_name='period',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timein_api.task'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timein_api.task'),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(upload_to='project_icons/'),
        ),
    ]
