# Generated by Django 4.0.5 on 2022-07-10 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0009_rename_range_comment_period_period_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timein_api.task'),
        ),
        migrations.AlterField(
            model_name='period',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timein_api.task'),
        ),
    ]
