# Generated by Django 4.0.5 on 2022-07-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timein_api', '0010_alter_comment_task_alter_period_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timein_api.project'),
        ),
    ]
